USE WAREHOUSE SYSTEM$STREAMLIT_NOTEBOOK_WHsssss;

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';
CREATE or replace ROLE cortex_user_role;
GRANT DATABASE ROLE SNOWFLAKE.COPILOT_USER TO ROLE CORTEX_USER_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CORTEX_USER_ROLE;




