-- ============================================================================
-- TML Fleet Telemetry V1 — Complete Setup Script
-- ============================================================================
-- NewCo Datawarehouse Workshop Demo — Tata Motors (Commercial Vehicle Telemetry)
--
-- Execute this script in order using a Snowflake worksheet or CLI.
-- Prerequisite: ACCOUNTADMIN role or equivalent privileges.
--
-- Steps:
--   1. Warehouse, Database, Schemas
--   2. Ingestion Service User (requires RSA public key — see README)
--   3. MASTER schema reference data
--   4. RAW schema landing table
--   5. CURATED schema views + dynamic tables
--   6. BUSINESSREADY schema dynamic tables + views
--   7. Governance: customer roles + row access policy
--   8. Retention enforcement: stored procedure + scheduled task
--   9. Verification queries
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- STEP 1: Warehouse, Database, Schemas
-- ────────────────────────────────────────────────────────────────────────────
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE TML_HACKATHON
    WAREHOUSE_SIZE = 'LARGE'
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE TML_FLEET_TELEMETRY;

USE WAREHOUSE TML_HACKATHON;

CREATE SCHEMA TML_FLEET_TELEMETRY.RAW;
CREATE SCHEMA TML_FLEET_TELEMETRY.CURATED;
CREATE SCHEMA TML_FLEET_TELEMETRY.BUSINESSREADY;
CREATE SCHEMA TML_FLEET_TELEMETRY.MASTER;

-- ────────────────────────────────────────────────────────────────────────────
-- STEP 2: Ingestion Service User
-- ────────────────────────────────────────────────────────────────────────────
-- IMPORTANT: Replace <RSA_PUBLIC_KEY_CONTENT> with the contents of rsa_key.pub
-- (excluding the BEGIN/END PUBLIC KEY lines).

CREATE USER IF NOT EXISTS TML_INGEST_USER
    TYPE = SERVICE
    RSA_PUBLIC_KEY = '<RSA_PUBLIC_KEY_CONTENT>';

CREATE ROLE IF NOT EXISTS TML_INGEST_ROLE;
GRANT ROLE TML_INGEST_ROLE TO USER TML_INGEST_USER;

GRANT USAGE ON WAREHOUSE TML_HACKATHON TO ROLE TML_INGEST_ROLE;
GRANT USAGE ON DATABASE TML_FLEET_TELEMETRY TO ROLE TML_INGEST_ROLE;
GRANT USAGE ON SCHEMA TML_FLEET_TELEMETRY.RAW TO ROLE TML_INGEST_ROLE;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA TML_FLEET_TELEMETRY.RAW TO ROLE TML_INGEST_ROLE;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA TML_FLEET_TELEMETRY.RAW TO ROLE TML_INGEST_ROLE;

-- ────────────────────────────────────────────────────────────────────────────
-- STEP 3: MASTER Schema — Reference Data
-- ────────────────────────────────────────────────────────────────────────────
USE SCHEMA TML_FLEET_TELEMETRY.MASTER;

-- 3a. Geofence Definitions (25 Indian cities)
CREATE OR REPLACE TABLE GEOFENCE_DEFINITIONS (
    GEOFENCE_ID VARCHAR,
    CITY_NAME VARCHAR,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    RADIUS_KM FLOAT,
    GEOFENCE_TYPE VARCHAR DEFAULT 'CITY_BOUNDARY',
    H3_CENTER_RES7 VARCHAR,
    H3_CENTER_RES9 VARCHAR,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
) COMMENT = 'Geofence definitions for trip-completion logic - Indian cities';

INSERT INTO GEOFENCE_DEFINITIONS (GEOFENCE_ID, CITY_NAME, LATITUDE, LONGITUDE, RADIUS_KM, H3_CENTER_RES7, H3_CENTER_RES9)
VALUES
('GF_AGR','Agra',27.1767,78.0081,15,'873d8584affffff','893d8584a87ffff'),
('GF_AHM','Ahmedabad',23.0225,72.5714,15,'8742cea64ffffff','8942cea6453ffff'),
('GF_BHU','Bhubaneswar',20.2961,85.8245,15,'873c8e400ffffff','893c8e400c3ffff'),
('GF_BLR','Bangalore',12.9716,77.5946,15,'8760145b4ffffff','8960145b483ffff'),
('GF_CHD','Chandigarh',30.7333,76.7794,15,'873d14699ffffff','893d14699c7ffff'),
('GF_CHE','Chennai',13.0827,80.2707,15,'87618c488ffffff','89618c48847ffff'),
('GF_DEL','Delhi',28.7041,77.1025,15,'873da18c3ffffff','893da18c333ffff'),
('GF_DUR','Durgapur',23.5204,87.3119,15,'873ca96e8ffffff','893ca96e823ffff'),
('GF_GOA','Goa',15.2993,74.124,15,'8760a989bffffff','8960a989b2fffff'),
('GF_HYD','Hyderabad',17.385,78.4867,15,'8760a25b0ffffff','8960a25b007ffff'),
('GF_IND','Indore',22.7196,75.8577,15,'873d9629bffffff','893d9629b83ffff'),
('GF_JAI','Jaipur',26.9124,75.7873,15,'873da218effffff','893da218ea7ffff'),
('GF_KOC','Kochi',9.9312,76.2673,15,'876004d33ffffff','896004d339bffff'),
('GF_KOL','Kolkata',22.5726,88.3639,15,'873cf2c60ffffff','893cf2c646fffff'),
('GF_LKN','Lucknow',26.8467,80.9462,15,'873d8dcd5ffffff','893d8dcd553ffff'),
('GF_MAD','Madurai',9.9252,78.1198,15,'87603422cffffff','89603422c3bffff'),
('GF_MUM','Mumbai',19.076,72.8777,15,'87608b0b6ffffff','89608b0b61bffff'),
('GF_MYS','Mysore',12.2958,76.6394,15,'876015d9dffffff','896015d9d2fffff'),
('GF_NAS','Nashik',19.9975,73.7898,15,'876099a04ffffff','896099a048fffff'),
('GF_PUN','Pune',18.5204,73.8567,15,'876088501ffffff','8960885016bffff'),
('GF_TRV','Trivandrum',8.5241,76.9366,15,'876026235ffffff','896026222dbffff'),
('GF_UDP','Udaipur',24.5854,73.7125,15,'873db66b4ffffff','893db679a6fffff'),
('GF_VIJ','Vijayawada',16.5062,80.648,15,'87619aa6cffffff','89619aa6c77ffff'),
('GF_VIZ','Visakhapatnam',17.6868,83.2185,15,'873c93014ffffff','893c9301423ffff'),
('GF_VNS','Varanasi',25.3176,82.9739,15,'873c16456ffffff','893c16456cfffff');

-- 3b. Road Segments (load from CSV)
CREATE OR REPLACE TABLE ROAD_SEGMENTS (
    SEGMENT_ID VARCHAR,
    ROUTE_NAME VARCHAR,
    HIGHWAY VARCHAR,
    FROM_CITY VARCHAR,
    TO_CITY VARCHAR,
    WAYPOINT_IDX NUMBER,
    START_LAT FLOAT,
    START_LON FLOAT,
    END_LAT FLOAT,
    END_LON FLOAT,
    MID_LAT FLOAT,
    MID_LON FLOAT,
    SEGMENT_KM FLOAT,
    H3_START_RES7 VARCHAR,
    H3_END_RES7 VARCHAR,
    H3_MID_RES7 VARCHAR,
    H3_MID_RES9 VARCHAR
) COMMENT = 'Road segment reference data for India - map matching for fuel efficiency analytics';

-- Load road_segments.csv via stage:
CREATE OR REPLACE TEMPORARY STAGE road_seg_stage;
-- Run from SnowSQL or Snowsight:
--   PUT file:///path/to/data/road_segments.csv @road_seg_stage;
--
-- Then load into a staging table and enrich with H3:
CREATE OR REPLACE TEMPORARY TABLE _road_seg_staging (
    SEGMENT_ID VARCHAR, ROUTE_NAME VARCHAR, HIGHWAY VARCHAR,
    FROM_CITY VARCHAR, TO_CITY VARCHAR, WAYPOINT_IDX NUMBER,
    START_LAT FLOAT, START_LON FLOAT, END_LAT FLOAT, END_LON FLOAT,
    MID_LAT FLOAT, MID_LON FLOAT, SEGMENT_KM FLOAT
);
-- COPY INTO _road_seg_staging FROM @road_seg_stage FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1);

INSERT INTO ROAD_SEGMENTS
SELECT
    SEGMENT_ID, ROUTE_NAME, HIGHWAY, FROM_CITY, TO_CITY, WAYPOINT_IDX,
    START_LAT, START_LON, END_LAT, END_LON, MID_LAT, MID_LON, SEGMENT_KM,
    H3_LATLNG_TO_CELL_STRING(START_LAT, START_LON, 7) AS H3_START_RES7,
    H3_LATLNG_TO_CELL_STRING(END_LAT, END_LON, 7) AS H3_END_RES7,
    H3_LATLNG_TO_CELL_STRING(MID_LAT, MID_LON, 7) AS H3_MID_RES7,
    H3_LATLNG_TO_CELL_STRING(MID_LAT, MID_LON, 9) AS H3_MID_RES9
FROM _road_seg_staging;

-- 3c. Customer Retention Policies (100 customers)
CREATE OR REPLACE TABLE CUSTOMER_RETENTION_POLICIES (
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    RAW_RETENTION_DAYS NUMBER DEFAULT 90
        COMMENT 'Days to retain raw telemetry',
    CURATED_RETENTION_DAYS NUMBER DEFAULT 365
        COMMENT 'Days to retain curated telemetry',
    TRIP_RETENTION_DAYS NUMBER DEFAULT 730
        COMMENT 'Days to retain trip summaries',
    VIDEO_RETENTION_DAYS NUMBER DEFAULT 30
        COMMENT 'Days to retain dashcam video',
    TENANT_ISOLATION_ENABLED BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Customer-specific data retention policies for multi-tenant isolation';

INSERT INTO CUSTOMER_RETENTION_POLICIES (CUSTOMER_ID, CUSTOMER_NAME, RAW_RETENTION_DAYS, CURATED_RETENTION_DAYS, VIDEO_RETENTION_DAYS)
SELECT
    'CUST_' || LPAD(SEQ4()::VARCHAR, 4, '0'),
    'Customer ' || SEQ4()::VARCHAR,
    CASE MOD(SEQ4(), 3) WHEN 0 THEN 90 WHEN 1 THEN 120 ELSE 180 END,
    CASE MOD(SEQ4(), 2) WHEN 0 THEN 365 ELSE 730 END,
    CASE MOD(SEQ4(), 3) WHEN 0 THEN 30 WHEN 1 THEN 30 ELSE 60 END
FROM TABLE(GENERATOR(ROWCOUNT => 100));

-- ────────────────────────────────────────────────────────────────────────────
-- STEP 4: RAW Schema — Landing Table
-- ────────────────────────────────────────────────────────────────────────────
USE SCHEMA TML_FLEET_TELEMETRY.RAW;

CREATE OR REPLACE TABLE VEHICLE_TELEMETRY_RAW_V1 (
    RECORD_METADATA VARIANT
        COMMENT 'Kafka metadata: offset, topic, partition, key, timestamp',
    EVENT_TS TIMESTAMP_NTZ(9),
    CUSTOMER_ID VARCHAR,
    VEHICLE_ID VARCHAR,
    DEVICE_ID VARCHAR,
    GPS_LATITUDE FLOAT,
    GPS_LONGITUDE FLOAT,
    GPS_ALTITUDE_M FLOAT,
    GPS_SPEED_KPH FLOAT,
    GPS_HEADING_DEG FLOAT,
    GPS_HDOP FLOAT,
    GPS_SATELLITE_COUNT NUMBER,
    GPS_FIX_QUALITY NUMBER,
    IMU_ACCEL_X_G FLOAT,
    IMU_ACCEL_Y_G FLOAT,
    IMU_ACCEL_Z_G FLOAT,
    IMU_GYRO_X_DPS FLOAT,
    IMU_GYRO_Y_DPS FLOAT,
    IMU_GYRO_Z_DPS FLOAT,
    J1939_VEHICLE_SPEED_KPH FLOAT,
    J1939_ENGINE_RPM FLOAT,
    J1939_ACCELERATOR_PEDAL_PCT FLOAT,
    J1939_ENGINE_LOAD_PCT FLOAT,
    J1939_ENGINE_TORQUE_PCT FLOAT,
    J1939_FUEL_RATE_LPH FLOAT,
    J1939_TOTAL_FUEL_USED_L FLOAT,
    J1939_FUEL_LEVEL_PCT FLOAT,
    J1939_COOLANT_TEMP_C FLOAT,
    J1939_OIL_TEMP_C FLOAT,
    J1939_OIL_PRESSURE_KPA FLOAT,
    J1939_INTAKE_MANIFOLD_PRESSURE_KPA FLOAT,
    J1939_BATTERY_VOLTAGE_V FLOAT,
    J1939_ENGINE_HOURS FLOAT,
    J1939_ODOMETER_KM FLOAT,
    J1939_GEAR_SELECTED NUMBER,
    J1939_BRAKE_SWITCH BOOLEAN,
    J1939_CLUTCH_SWITCH BOOLEAN,
    J1939_PTO_STATUS BOOLEAN,
    J1939_ACTIVE_DTC_COUNT NUMBER,
    TEL_IGNITION_STATUS VARCHAR,
    TEL_EXTERNAL_POWER_V FLOAT,
    TEL_BACKUP_BATTERY_V FLOAT,
    TEL_DEVICE_TEMP_C FLOAT,
    TEL_GSM_SIGNAL_DBM FLOAT,
    TEL_NETWORK_TYPE VARCHAR,
    TEL_GNSS_FIX_STATUS VARCHAR,
    TEL_CAN_BUS_HEALTH VARCHAR,
    TEL_STORAGE_QUEUE_DEPTH NUMBER,
    TEL_TAMPER_ALERT BOOLEAN,
    INGEST_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
) CLUSTER BY (VEHICLE_ID, EVENT_TS)
ENABLE_SCHEMA_EVOLUTION = TRUE
CHANGE_TRACKING = TRUE
COMMENT = 'V1: Single-topic combined telemetry with prefixed columns. Schema evolution adds J1939 tire pressure + DEF columns in Phase 2.';

-- ────────────────────────────────────────────────────────────────────────────
-- STEP 5: CURATED Schema — Views (ARRIVED_LATE Flag)
-- ────────────────────────────────────────────────────────────────────────────
USE SCHEMA TML_FLEET_TELEMETRY.CURATED;

CREATE OR REPLACE VIEW VW_GPS_SIGNALS_V1 AS
SELECT
    EVENT_TS, CUSTOMER_ID, VEHICLE_ID, DEVICE_ID, INGEST_TS,
    GPS_LATITUDE, GPS_LONGITUDE, GPS_ALTITUDE_M, GPS_SPEED_KPH,
    GPS_HEADING_DEG, GPS_HDOP, GPS_SATELLITE_COUNT, GPS_FIX_QUALITY,
    CASE WHEN ABS(DATEDIFF('second', EVENT_TS, INGEST_TS)) > 25400
         THEN TRUE ELSE FALSE END AS ARRIVED_LATE
FROM TML_FLEET_TELEMETRY.RAW.VEHICLE_TELEMETRY_RAW_V1;

CREATE OR REPLACE VIEW VW_IMU_SIGNALS_V1 AS
SELECT
    EVENT_TS, CUSTOMER_ID, VEHICLE_ID, DEVICE_ID, INGEST_TS,
    IMU_ACCEL_X_G, IMU_ACCEL_Y_G, IMU_ACCEL_Z_G,
    IMU_GYRO_X_DPS, IMU_GYRO_Y_DPS, IMU_GYRO_Z_DPS,
    CASE WHEN ABS(DATEDIFF('second', EVENT_TS, INGEST_TS)) > 25400
         THEN TRUE ELSE FALSE END AS ARRIVED_LATE
FROM TML_FLEET_TELEMETRY.RAW.VEHICLE_TELEMETRY_RAW_V1;

CREATE OR REPLACE VIEW VW_J1939_SIGNALS_V1 AS
SELECT
    EVENT_TS, CUSTOMER_ID, VEHICLE_ID, DEVICE_ID, INGEST_TS,
    J1939_VEHICLE_SPEED_KPH, J1939_ENGINE_RPM, J1939_ACCELERATOR_PEDAL_PCT,
    J1939_ENGINE_LOAD_PCT, J1939_ENGINE_TORQUE_PCT, J1939_FUEL_RATE_LPH,
    J1939_TOTAL_FUEL_USED_L, J1939_FUEL_LEVEL_PCT, J1939_COOLANT_TEMP_C,
    J1939_OIL_TEMP_C, J1939_OIL_PRESSURE_KPA, J1939_INTAKE_MANIFOLD_PRESSURE_KPA,
    J1939_BATTERY_VOLTAGE_V, J1939_ENGINE_HOURS, J1939_ODOMETER_KM,
    J1939_GEAR_SELECTED, J1939_BRAKE_SWITCH, J1939_CLUTCH_SWITCH,
    J1939_PTO_STATUS, J1939_ACTIVE_DTC_COUNT,
    J1939_TYRE_PRESSURE_FRONT_LEFT_KPA, J1939_TYRE_PRESSURE_FRONT_RIGHT_KPA,
    J1939_TYRE_PRESSURE_REAR_LEFT_KPA, J1939_TYRE_PRESSURE_REAR_RIGHT_KPA,
    J1939_DEF_LEVEL_PCT,
    CASE WHEN ABS(DATEDIFF('second', EVENT_TS, INGEST_TS)) > 25400
         THEN TRUE ELSE FALSE END AS ARRIVED_LATE
FROM TML_FLEET_TELEMETRY.RAW.VEHICLE_TELEMETRY_RAW_V1;

CREATE OR REPLACE VIEW VW_TELEMATICS_V1 AS
SELECT
    EVENT_TS, CUSTOMER_ID, VEHICLE_ID, DEVICE_ID, INGEST_TS,
    TEL_IGNITION_STATUS, TEL_EXTERNAL_POWER_V, TEL_BACKUP_BATTERY_V,
    TEL_DEVICE_TEMP_C, TEL_GSM_SIGNAL_DBM, TEL_NETWORK_TYPE,
    TEL_GNSS_FIX_STATUS, TEL_CAN_BUS_HEALTH, TEL_STORAGE_QUEUE_DEPTH,
    TEL_TAMPER_ALERT,
    CASE WHEN ABS(DATEDIFF('second', EVENT_TS, INGEST_TS)) > 25400
         THEN TRUE ELSE FALSE END AS ARRIVED_LATE
FROM TML_FLEET_TELEMETRY.RAW.VEHICLE_TELEMETRY_RAW_V1;

-- ────────────────────────────────────────────────────────────────────────────
-- STEP 6: CURATED Schema — Dynamic Tables (Dedup, INCREMENTAL)
-- ────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE DYNAMIC TABLE TML_FLEET_TELEMETRY.CURATED.GPS_SIGNALS_V1
    TARGET_LAG = '1 minute'
    WAREHOUSE = TML_HACKATHON
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
AS
SELECT * FROM TML_FLEET_TELEMETRY.CURATED.VW_GPS_SIGNALS_V1
QUALIFY ROW_NUMBER() OVER (PARTITION BY VEHICLE_ID, EVENT_TS ORDER BY INGEST_TS DESC) = 1;

CREATE OR REPLACE DYNAMIC TABLE TML_FLEET_TELEMETRY.CURATED.IMU_SIGNALS_V1
    TARGET_LAG = '1 minute'
    WAREHOUSE = TML_HACKATHON
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
AS
SELECT * FROM TML_FLEET_TELEMETRY.CURATED.VW_IMU_SIGNALS_V1
QUALIFY ROW_NUMBER() OVER (PARTITION BY VEHICLE_ID, EVENT_TS ORDER BY INGEST_TS DESC) = 1;

CREATE OR REPLACE DYNAMIC TABLE TML_FLEET_TELEMETRY.CURATED.J1939_SIGNALS_V1
    TARGET_LAG = '1 minute'
    WAREHOUSE = TML_HACKATHON
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
AS
SELECT * FROM TML_FLEET_TELEMETRY.CURATED.VW_J1939_SIGNALS_V1
QUALIFY ROW_NUMBER() OVER (PARTITION BY VEHICLE_ID, EVENT_TS ORDER BY INGEST_TS DESC) = 1;

CREATE OR REPLACE DYNAMIC TABLE TML_FLEET_TELEMETRY.CURATED.TELEMATICS_DEVICE_PARAMS_V1
    TARGET_LAG = '1 minute'
    WAREHOUSE = TML_HACKATHON
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
AS
SELECT * FROM TML_FLEET_TELEMETRY.CURATED.VW_TELEMATICS_V1
QUALIFY ROW_NUMBER() OVER (PARTITION BY VEHICLE_ID, EVENT_TS ORDER BY INGEST_TS DESC) = 1;

-- ────────────────────────────────────────────────────────────────────────────
-- STEP 7: BUSINESSREADY Schema — Dynamic Tables
-- ────────────────────────────────────────────────────────────────────────────
USE SCHEMA TML_FLEET_TELEMETRY.BUSINESSREADY;

-- 7a. FACT_VEHICLE_DAILY_METRICS_V1
CREATE OR REPLACE DYNAMIC TABLE FACT_VEHICLE_DAILY_METRICS_V1
    TARGET_LAG = '5 minutes'
    WAREHOUSE = TML_HACKATHON
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
AS
SELECT
    j.CUSTOMER_ID, j.VEHICLE_ID,
    DATE_TRUNC('DAY', j.EVENT_TS) AS METRIC_DATE,
    COUNT(*) AS TOTAL_READINGS,
    ROUND(AVG(j.J1939_VEHICLE_SPEED_KPH), 1) AS AVG_SPEED_KPH,
    ROUND(MAX(j.J1939_VEHICLE_SPEED_KPH), 1) AS MAX_SPEED_KPH,
    ROUND(AVG(j.J1939_ENGINE_RPM), 0) AS AVG_ENGINE_RPM,
    ROUND(MAX(j.J1939_ENGINE_RPM), 0) AS MAX_ENGINE_RPM,
    ROUND(AVG(j.J1939_ENGINE_LOAD_PCT), 1) AS AVG_ENGINE_LOAD_PCT,
    ROUND(AVG(j.J1939_FUEL_RATE_LPH), 2) AS AVG_FUEL_RATE_LPH,
    ROUND(MAX(j.J1939_TOTAL_FUEL_USED_L) - MIN(j.J1939_TOTAL_FUEL_USED_L), 2) AS DAILY_FUEL_CONSUMED_L,
    ROUND(MAX(j.J1939_ODOMETER_KM) - MIN(j.J1939_ODOMETER_KM), 2) AS DAILY_DISTANCE_KM,
    ROUND(AVG(j.J1939_COOLANT_TEMP_C), 1) AS AVG_COOLANT_TEMP_C,
    ROUND(MAX(j.J1939_COOLANT_TEMP_C), 1) AS MAX_COOLANT_TEMP_C,
    ROUND(AVG(j.J1939_BATTERY_VOLTAGE_V), 2) AS AVG_BATTERY_V,
    ROUND(MAX(j.J1939_ENGINE_HOURS) - MIN(j.J1939_ENGINE_HOURS), 2) AS DAILY_ENGINE_HOURS,
    SUM(CASE WHEN j.J1939_BRAKE_SWITCH = TRUE THEN 1 ELSE 0 END) AS BRAKE_EVENTS,
    MAX(j.J1939_ACTIVE_DTC_COUNT) AS MAX_DTC_COUNT,
    ROUND(AVG(j.J1939_TYRE_PRESSURE_FRONT_LEFT_KPA), 1) AS AVG_TYRE_FL_KPA,
    ROUND(AVG(j.J1939_TYRE_PRESSURE_FRONT_RIGHT_KPA), 1) AS AVG_TYRE_FR_KPA,
    ROUND(AVG(j.J1939_TYRE_PRESSURE_REAR_LEFT_KPA), 1) AS AVG_TYRE_RL_KPA,
    ROUND(AVG(j.J1939_TYRE_PRESSURE_REAR_RIGHT_KPA), 1) AS AVG_TYRE_RR_KPA,
    ROUND(AVG(j.J1939_DEF_LEVEL_PCT), 1) AS AVG_DEF_LEVEL_PCT
FROM TML_FLEET_TELEMETRY.CURATED.J1939_SIGNALS_V1 j
GROUP BY j.CUSTOMER_ID, j.VEHICLE_ID, DATE_TRUNC('DAY', j.EVENT_TS);

-- 7b. FACT_CUSTOMER_FLEET_SUMMARY_V1
CREATE OR REPLACE DYNAMIC TABLE FACT_CUSTOMER_FLEET_SUMMARY_V1
    TARGET_LAG = '5 minutes'
    WAREHOUSE = TML_HACKATHON
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
AS
SELECT
    j.CUSTOMER_ID,
    DATE_TRUNC('DAY', j.EVENT_TS) AS METRIC_DATE,
    COUNT(DISTINCT j.VEHICLE_ID) AS ACTIVE_VEHICLES,
    COUNT(*) AS TOTAL_READINGS,
    ROUND(AVG(j.J1939_VEHICLE_SPEED_KPH), 1) AS FLEET_AVG_SPEED_KPH,
    ROUND(AVG(j.J1939_FUEL_RATE_LPH), 2) AS FLEET_AVG_FUEL_RATE_LPH,
    ROUND(SUM(COALESCE(j.J1939_TOTAL_FUEL_USED_L, 0)), 0) AS FLEET_TOTAL_FUEL_L,
    ROUND(AVG(j.J1939_ENGINE_LOAD_PCT), 1) AS FLEET_AVG_ENGINE_LOAD_PCT,
    ROUND(AVG(j.J1939_COOLANT_TEMP_C), 1) AS FLEET_AVG_COOLANT_TEMP_C,
    SUM(CASE WHEN j.J1939_ACTIVE_DTC_COUNT > 0 THEN 1 ELSE 0 END) AS READINGS_WITH_DTC,
    ROUND(AVG(j.J1939_BATTERY_VOLTAGE_V), 2) AS FLEET_AVG_BATTERY_V,
    SUM(CASE WHEN j.J1939_BRAKE_SWITCH = TRUE THEN 1 ELSE 0 END) AS FLEET_BRAKE_EVENTS,
    ROUND(AVG(j.J1939_TYRE_PRESSURE_FRONT_LEFT_KPA), 1) AS FLEET_AVG_TYRE_FL_KPA,
    ROUND(AVG(j.J1939_DEF_LEVEL_PCT), 1) AS FLEET_AVG_DEF_LEVEL_PCT
FROM TML_FLEET_TELEMETRY.CURATED.J1939_SIGNALS_V1 j
GROUP BY j.CUSTOMER_ID, DATE_TRUNC('DAY', j.EVENT_TS);

-- 7c. DIM_VEHICLE_V1
CREATE OR REPLACE DYNAMIC TABLE DIM_VEHICLE_V1
    TARGET_LAG = '5 minutes'
    WAREHOUSE = TML_HACKATHON
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
AS
SELECT DISTINCT
    v.VEHICLE_ID, v.CUSTOMER_ID, v.DEVICE_ID,
    c.CUSTOMER_NAME, c.RAW_RETENTION_DAYS, c.CURATED_RETENTION_DAYS,
    c.TRIP_RETENTION_DAYS, c.TENANT_ISOLATION_ENABLED,
    MIN(v.EVENT_TS) AS FIRST_SEEN_TS,
    MAX(v.EVENT_TS) AS LAST_SEEN_TS,
    COUNT(*) AS TOTAL_GPS_EVENTS
FROM TML_FLEET_TELEMETRY.CURATED.GPS_SIGNALS_V1 v
LEFT JOIN TML_FLEET_TELEMETRY.MASTER.CUSTOMER_RETENTION_POLICIES c
    ON c.CUSTOMER_ID = v.CUSTOMER_ID
GROUP BY v.VEHICLE_ID, v.CUSTOMER_ID, v.DEVICE_ID,
    c.CUSTOMER_NAME, c.RAW_RETENTION_DAYS, c.CURATED_RETENTION_DAYS,
    c.TRIP_RETENTION_DAYS, c.TENANT_ISOLATION_ENABLED;

-- 7d. DIM_CUSTOMER_V1
CREATE OR REPLACE DYNAMIC TABLE DIM_CUSTOMER_V1
    TARGET_LAG = '5 minutes'
    WAREHOUSE = TML_HACKATHON
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
AS
SELECT
    c.CUSTOMER_ID, c.CUSTOMER_NAME,
    c.RAW_RETENTION_DAYS, c.CURATED_RETENTION_DAYS,
    c.TRIP_RETENTION_DAYS, c.VIDEO_RETENTION_DAYS,
    c.TENANT_ISOLATION_ENABLED, c.CREATED_AT,
    f.FLEET_SIZE, f.ACTIVE_VEHICLES, f.TOTAL_EVENTS
FROM TML_FLEET_TELEMETRY.MASTER.CUSTOMER_RETENTION_POLICIES c
LEFT JOIN (
    SELECT CUSTOMER_ID,
        COUNT(DISTINCT VEHICLE_ID) AS FLEET_SIZE,
        COUNT(DISTINCT CASE WHEN EVENT_TS >= DATEADD('DAY', -7, CURRENT_TIMESTAMP()) THEN VEHICLE_ID END) AS ACTIVE_VEHICLES,
        COUNT(*) AS TOTAL_EVENTS
    FROM TML_FLEET_TELEMETRY.CURATED.GPS_SIGNALS_V1
    GROUP BY CUSTOMER_ID
) f ON f.CUSTOMER_ID = c.CUSTOMER_ID;

-- 7e. FLEET_HEALTH_DASHBOARD_V1
CREATE OR REPLACE DYNAMIC TABLE FLEET_HEALTH_DASHBOARD_V1
    TARGET_LAG = '10 minutes'
    WAREHOUSE = TML_HACKATHON
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
    COMMENT = 'Fleet health overview: per-vehicle health status based on DTC counts, CAN bus health, battery, coolant, tamper alerts, and connectivity.'
AS
WITH latest_j1939 AS (
    SELECT CUSTOMER_ID, VEHICLE_ID, DEVICE_ID,
        MAX(EVENT_TS) AS LAST_EVENT_TS,
        MAX(J1939_ACTIVE_DTC_COUNT) AS MAX_DTC_COUNT,
        MAX(J1939_COOLANT_TEMP_C) AS MAX_COOLANT_TEMP_C,
        MIN(J1939_BATTERY_VOLTAGE_V) AS MIN_BATTERY_VOLTAGE_V,
        MAX(J1939_ODOMETER_KM) AS CURRENT_ODOMETER_KM,
        MAX(J1939_ENGINE_HOURS) AS CURRENT_ENGINE_HOURS
    FROM TML_FLEET_TELEMETRY.CURATED.J1939_SIGNALS_V1
    GROUP BY CUSTOMER_ID, VEHICLE_ID, DEVICE_ID
),
latest_telematics AS (
    SELECT VEHICLE_ID,
        AVG(TEL_GSM_SIGNAL_DBM) AS AVG_GSM_SIGNAL_DBM,
        MAX(TEL_STORAGE_QUEUE_DEPTH) AS MAX_QUEUE_DEPTH,
        BOOLAND_AGG(CASE WHEN TEL_CAN_BUS_HEALTH = 'HEALTHY' THEN TRUE ELSE FALSE END) AS ALL_CAN_HEALTHY,
        BOOLOR_AGG(COALESCE(TEL_TAMPER_ALERT, FALSE)) AS HAS_TAMPER_ALERT
    FROM TML_FLEET_TELEMETRY.CURATED.TELEMATICS_DEVICE_PARAMS_V1
    GROUP BY VEHICLE_ID
)
SELECT
    j.CUSTOMER_ID, j.VEHICLE_ID, j.DEVICE_ID, j.LAST_EVENT_TS,
    DATEDIFF('MINUTE', j.LAST_EVENT_TS, CURRENT_TIMESTAMP()) AS MINUTES_SINCE_LAST_EVENT,
    COALESCE(j.MAX_DTC_COUNT, 0) AS MAX_DTC_COUNT,
    NOT t.ALL_CAN_HEALTHY AS HAS_CAN_BUS_ISSUES,
    t.HAS_TAMPER_ALERT,
    ROUND(j.MAX_COOLANT_TEMP_C, 1) AS MAX_COOLANT_TEMP_C,
    ROUND(j.MIN_BATTERY_VOLTAGE_V, 1) AS MIN_BATTERY_VOLTAGE_V,
    ROUND(t.AVG_GSM_SIGNAL_DBM, 1) AS AVG_GSM_SIGNAL_DBM,
    t.MAX_QUEUE_DEPTH,
    ROUND(j.CURRENT_ODOMETER_KM, 0) AS CURRENT_ODOMETER_KM,
    ROUND(j.CURRENT_ENGINE_HOURS, 0) AS CURRENT_ENGINE_HOURS,
    CASE
        WHEN COALESCE(j.MAX_DTC_COUNT, 0) > 5 OR t.HAS_TAMPER_ALERT THEN 'CRITICAL'
        WHEN COALESCE(j.MAX_DTC_COUNT, 0) > 2 OR NOT t.ALL_CAN_HEALTHY THEN 'WARNING'
        WHEN j.MAX_COOLANT_TEMP_C > 105 OR j.MIN_BATTERY_VOLTAGE_V < 22 THEN 'ALERT'
        ELSE 'HEALTHY'
    END AS HEALTH_STATUS
FROM latest_j1939 j
LEFT JOIN latest_telematics t ON j.VEHICLE_ID = t.VEHICLE_ID;

-- 7f. TRIP_SUMMARIES_V1
CREATE OR REPLACE DYNAMIC TABLE TRIP_SUMMARIES_V1
    TARGET_LAG = '2 minutes'
    WAREHOUSE = TML_HACKATHON
    REFRESH_MODE = AUTO
    INITIALIZE = ON_CREATE
AS
WITH ignition_transitions AS (
    SELECT t.CUSTOMER_ID, t.VEHICLE_ID, t.EVENT_TS, t.TEL_IGNITION_STATUS,
        CASE WHEN t.TEL_IGNITION_STATUS = 'ON'
            AND (LAG(t.TEL_IGNITION_STATUS) OVER (PARTITION BY t.VEHICLE_ID ORDER BY t.EVENT_TS) = 'OFF'
                 OR LAG(t.TEL_IGNITION_STATUS) OVER (PARTITION BY t.VEHICLE_ID ORDER BY t.EVENT_TS) IS NULL)
            THEN 1 ELSE 0
        END AS TRIP_START_FLAG
    FROM TML_FLEET_TELEMETRY.CURATED.TELEMATICS_DEVICE_PARAMS_V1 t
),
trip_groups AS (
    SELECT *, SUM(TRIP_START_FLAG) OVER (PARTITION BY VEHICLE_ID ORDER BY EVENT_TS) AS TRIP_NUM
    FROM ignition_transitions WHERE TEL_IGNITION_STATUS = 'ON'
),
trip_boundaries AS (
    SELECT CUSTOMER_ID, VEHICLE_ID, TRIP_NUM,
        MIN(EVENT_TS) AS TRIP_START_TS, MAX(EVENT_TS) AS TRIP_END_TS
    FROM trip_groups WHERE TRIP_NUM > 0
    GROUP BY CUSTOMER_ID, VEHICLE_ID, TRIP_NUM
),
trip_gps AS (
    SELECT tb.CUSTOMER_ID, tb.VEHICLE_ID, tb.TRIP_NUM,
        tb.TRIP_START_TS, tb.TRIP_END_TS,
        TIMESTAMPDIFF('SECOND', tb.TRIP_START_TS, tb.TRIP_END_TS) AS DURATION_SEC,
        FIRST_VALUE(g.GPS_LATITUDE) OVER (PARTITION BY tb.VEHICLE_ID, tb.TRIP_NUM ORDER BY g.EVENT_TS) AS START_LAT,
        FIRST_VALUE(g.GPS_LONGITUDE) OVER (PARTITION BY tb.VEHICLE_ID, tb.TRIP_NUM ORDER BY g.EVENT_TS) AS START_LON,
        LAST_VALUE(g.GPS_LATITUDE) OVER (PARTITION BY tb.VEHICLE_ID, tb.TRIP_NUM ORDER BY g.EVENT_TS ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS END_LAT,
        LAST_VALUE(g.GPS_LONGITUDE) OVER (PARTITION BY tb.VEHICLE_ID, tb.TRIP_NUM ORDER BY g.EVENT_TS ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS END_LON,
        ROW_NUMBER() OVER (PARTITION BY tb.VEHICLE_ID, tb.TRIP_NUM ORDER BY g.EVENT_TS) AS gps_rn
    FROM trip_boundaries tb
    JOIN TML_FLEET_TELEMETRY.CURATED.GPS_SIGNALS_V1 g
        ON g.VEHICLE_ID = tb.VEHICLE_ID AND g.EVENT_TS BETWEEN tb.TRIP_START_TS AND tb.TRIP_END_TS
),
trip_j1939 AS (
    SELECT tb.VEHICLE_ID, tb.TRIP_NUM,
        MAX(j.J1939_ODOMETER_KM) - MIN(j.J1939_ODOMETER_KM) AS DISTANCE_KM,
        MAX(j.J1939_TOTAL_FUEL_USED_L) - MIN(j.J1939_TOTAL_FUEL_USED_L) AS FUEL_CONSUMED_L,
        AVG(j.J1939_VEHICLE_SPEED_KPH) AS AVG_SPEED_KPH,
        MAX(j.J1939_VEHICLE_SPEED_KPH) AS MAX_SPEED_KPH,
        AVG(j.J1939_ENGINE_RPM) AS AVG_ENGINE_RPM,
        AVG(j.J1939_ENGINE_LOAD_PCT) AS AVG_ENGINE_LOAD_PCT
    FROM trip_boundaries tb
    JOIN TML_FLEET_TELEMETRY.CURATED.J1939_SIGNALS_V1 j
        ON j.VEHICLE_ID = tb.VEHICLE_ID AND j.EVENT_TS BETWEEN tb.TRIP_START_TS AND tb.TRIP_END_TS
    GROUP BY tb.VEHICLE_ID, tb.TRIP_NUM
),
trip_geofence_start AS (
    SELECT DISTINCT tb.VEHICLE_ID, tb.TRIP_NUM, gf.CITY_NAME AS START_GEOFENCE
    FROM trip_boundaries tb
    JOIN TML_FLEET_TELEMETRY.CURATED.GPS_SIGNALS_V1 g ON g.VEHICLE_ID = tb.VEHICLE_ID AND g.EVENT_TS = tb.TRIP_START_TS
    JOIN TML_FLEET_TELEMETRY.MASTER.GEOFENCE_DEFINITIONS gf ON HAVERSINE(g.GPS_LATITUDE, g.GPS_LONGITUDE, gf.LATITUDE, gf.LONGITUDE) <= gf.RADIUS_KM
    QUALIFY ROW_NUMBER() OVER (PARTITION BY tb.VEHICLE_ID, tb.TRIP_NUM ORDER BY HAVERSINE(g.GPS_LATITUDE, g.GPS_LONGITUDE, gf.LATITUDE, gf.LONGITUDE)) = 1
),
trip_geofence_end AS (
    SELECT DISTINCT tb.VEHICLE_ID, tb.TRIP_NUM, gf.CITY_NAME AS END_GEOFENCE
    FROM trip_boundaries tb
    JOIN TML_FLEET_TELEMETRY.CURATED.GPS_SIGNALS_V1 g ON g.VEHICLE_ID = tb.VEHICLE_ID AND g.EVENT_TS = tb.TRIP_END_TS
    JOIN TML_FLEET_TELEMETRY.MASTER.GEOFENCE_DEFINITIONS gf ON HAVERSINE(g.GPS_LATITUDE, g.GPS_LONGITUDE, gf.LATITUDE, gf.LONGITUDE) <= gf.RADIUS_KM
    QUALIFY ROW_NUMBER() OVER (PARTITION BY tb.VEHICLE_ID, tb.TRIP_NUM ORDER BY HAVERSINE(g.GPS_LATITUDE, g.GPS_LONGITUDE, gf.LATITUDE, gf.LONGITUDE)) = 1
)
SELECT
    tg.CUSTOMER_ID, tg.VEHICLE_ID, tg.TRIP_NUM,
    tg.TRIP_START_TS, tg.TRIP_END_TS, tg.DURATION_SEC,
    ROUND(tg.DURATION_SEC / 60.0, 1) AS DURATION_MIN,
    tg.START_LAT, tg.START_LON, tg.END_LAT, tg.END_LON,
    ROUND(tj.DISTANCE_KM, 2) AS DISTANCE_KM,
    ROUND(tj.FUEL_CONSUMED_L, 2) AS FUEL_CONSUMED_L,
    CASE WHEN tj.DISTANCE_KM > 0 THEN ROUND(tj.FUEL_CONSUMED_L / tj.DISTANCE_KM * 100, 2) END AS FUEL_EFFICIENCY_L_PER_100KM,
    ROUND(tj.AVG_SPEED_KPH, 1) AS AVG_SPEED_KPH,
    ROUND(tj.MAX_SPEED_KPH, 1) AS MAX_SPEED_KPH,
    ROUND(tj.AVG_ENGINE_RPM, 0) AS AVG_ENGINE_RPM,
    ROUND(tj.AVG_ENGINE_LOAD_PCT, 1) AS AVG_ENGINE_LOAD_PCT,
    gs.START_GEOFENCE, ge.END_GEOFENCE
FROM trip_gps tg
LEFT JOIN trip_j1939 tj ON tg.VEHICLE_ID = tj.VEHICLE_ID AND tg.TRIP_NUM = tj.TRIP_NUM
LEFT JOIN trip_geofence_start gs ON tg.VEHICLE_ID = gs.VEHICLE_ID AND tg.TRIP_NUM = gs.TRIP_NUM
LEFT JOIN trip_geofence_end ge ON tg.VEHICLE_ID = ge.VEHICLE_ID AND tg.TRIP_NUM = ge.TRIP_NUM
WHERE tg.gps_rn = 1;

-- ────────────────────────────────────────────────────────────────────────────
-- STEP 8: BUSINESSREADY Schema — Views
-- ────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW VEHICLE360_V1 AS
SELECT
    dv.VEHICLE_ID, dv.CUSTOMER_ID, dv.DEVICE_ID, dv.CUSTOMER_NAME,
    dv.FIRST_SEEN_TS, dv.LAST_SEEN_TS, dv.TOTAL_GPS_EVENTS,
    fm.METRIC_DATE, fm.TOTAL_READINGS, fm.AVG_SPEED_KPH, fm.MAX_SPEED_KPH,
    fm.AVG_ENGINE_RPM, fm.AVG_ENGINE_LOAD_PCT, fm.AVG_FUEL_RATE_LPH,
    fm.DAILY_FUEL_CONSUMED_L, fm.DAILY_DISTANCE_KM,
    CASE WHEN fm.DAILY_DISTANCE_KM > 0
        THEN ROUND(fm.DAILY_FUEL_CONSUMED_L / fm.DAILY_DISTANCE_KM * 100, 2)
    END AS FUEL_EFFICIENCY_L_PER_100KM,
    fm.AVG_COOLANT_TEMP_C, fm.MAX_COOLANT_TEMP_C, fm.AVG_BATTERY_V,
    fm.DAILY_ENGINE_HOURS, fm.BRAKE_EVENTS, fm.MAX_DTC_COUNT,
    fm.AVG_TYRE_FL_KPA, fm.AVG_TYRE_FR_KPA, fm.AVG_TYRE_RL_KPA,
    fm.AVG_TYRE_RR_KPA, fm.AVG_DEF_LEVEL_PCT
FROM TML_FLEET_TELEMETRY.BUSINESSREADY.DIM_VEHICLE_V1 dv
LEFT JOIN TML_FLEET_TELEMETRY.BUSINESSREADY.FACT_VEHICLE_DAILY_METRICS_V1 fm
    ON fm.VEHICLE_ID = dv.VEHICLE_ID;

CREATE OR REPLACE VIEW CUSTOMER360_V1 AS
SELECT
    dc.CUSTOMER_ID, dc.CUSTOMER_NAME, dc.FLEET_SIZE, dc.ACTIVE_VEHICLES,
    dc.TOTAL_EVENTS, dc.RAW_RETENTION_DAYS, dc.CURATED_RETENTION_DAYS,
    dc.TRIP_RETENTION_DAYS, dc.TENANT_ISOLATION_ENABLED,
    fs.METRIC_DATE, fs.ACTIVE_VEHICLES AS DAILY_ACTIVE_VEHICLES,
    fs.TOTAL_READINGS AS DAILY_READINGS,
    fs.FLEET_AVG_SPEED_KPH, fs.FLEET_AVG_FUEL_RATE_LPH, fs.FLEET_TOTAL_FUEL_L,
    fs.FLEET_AVG_ENGINE_LOAD_PCT, fs.FLEET_AVG_COOLANT_TEMP_C,
    fs.READINGS_WITH_DTC, fs.FLEET_AVG_BATTERY_V, fs.FLEET_BRAKE_EVENTS,
    fs.FLEET_AVG_TYRE_FL_KPA, fs.FLEET_AVG_DEF_LEVEL_PCT
FROM TML_FLEET_TELEMETRY.BUSINESSREADY.DIM_CUSTOMER_V1 dc
LEFT JOIN TML_FLEET_TELEMETRY.BUSINESSREADY.FACT_CUSTOMER_FLEET_SUMMARY_V1 fs
    ON fs.CUSTOMER_ID = dc.CUSTOMER_ID;

CREATE OR REPLACE VIEW MONTHLY_ROAD_SEGMENT_FUEL_EFFICIENCY_V1 AS
WITH gps_with_h3 AS (
    SELECT g.VEHICLE_ID, g.CUSTOMER_ID, g.EVENT_TS, g.GPS_LATITUDE, g.GPS_LONGITUDE,
        H3_LATLNG_TO_CELL_STRING(g.GPS_LATITUDE, g.GPS_LONGITUDE, 7) AS H3_RES7,
        DATE_TRUNC('MONTH', g.EVENT_TS) AS MONTH_START
    FROM TML_FLEET_TELEMETRY.CURATED.GPS_SIGNALS_V1 g
),
gps_on_segment AS (
    SELECT gh.VEHICLE_ID, gh.CUSTOMER_ID, gh.EVENT_TS, gh.MONTH_START,
        gh.GPS_LATITUDE, gh.GPS_LONGITUDE,
        rs.SEGMENT_ID, rs.ROUTE_NAME, rs.HIGHWAY, rs.FROM_CITY, rs.TO_CITY, rs.SEGMENT_KM
    FROM gps_with_h3 gh
    JOIN TML_FLEET_TELEMETRY.MASTER.ROAD_SEGMENTS rs ON gh.H3_RES7 = rs.H3_MID_RES7
),
segment_j1939 AS (
    SELECT gs.VEHICLE_ID, gs.CUSTOMER_ID, gs.MONTH_START,
        gs.SEGMENT_ID, gs.ROUTE_NAME, gs.HIGHWAY, gs.FROM_CITY, gs.TO_CITY, gs.SEGMENT_KM,
        j.J1939_FUEL_RATE_LPH, j.J1939_VEHICLE_SPEED_KPH, j.J1939_ENGINE_LOAD_PCT
    FROM gps_on_segment gs
    JOIN TML_FLEET_TELEMETRY.CURATED.J1939_SIGNALS_V1 j
        ON j.VEHICLE_ID = gs.VEHICLE_ID AND j.EVENT_TS = gs.EVENT_TS
)
SELECT MONTH_START, SEGMENT_ID, ROUTE_NAME, HIGHWAY, FROM_CITY, TO_CITY, SEGMENT_KM,
    COUNT(DISTINCT VEHICLE_ID) AS UNIQUE_VEHICLES,
    COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
    COUNT(*) AS TOTAL_READINGS,
    ROUND(AVG(J1939_FUEL_RATE_LPH), 2) AS AVG_FUEL_RATE_LPH,
    ROUND(AVG(J1939_VEHICLE_SPEED_KPH), 1) AS AVG_SPEED_KPH,
    ROUND(AVG(J1939_ENGINE_LOAD_PCT), 1) AS AVG_ENGINE_LOAD_PCT,
    CASE WHEN AVG(J1939_VEHICLE_SPEED_KPH) > 0
        THEN ROUND(AVG(J1939_FUEL_RATE_LPH) / AVG(J1939_VEHICLE_SPEED_KPH) * 100, 2)
    END AS FUEL_EFFICIENCY_L_PER_100KM
FROM segment_j1939
GROUP BY MONTH_START, SEGMENT_ID, ROUTE_NAME, HIGHWAY, FROM_CITY, TO_CITY, SEGMENT_KM
ORDER BY MONTH_START, ROUTE_NAME, SEGMENT_ID;

-- ────────────────────────────────────────────────────────────────────────────
-- STEP 9: Governance — Customer Roles and Row Access Policy
-- ────────────────────────────────────────────────────────────────────────────

-- Create 100 customer roles
DECLARE
    i INT DEFAULT 1;
BEGIN
    WHILE (i <= 100) DO
        LET role_name := 'CUST_' || LPAD(i::VARCHAR, 4, '0') || '_ROLE';
        EXECUTE IMMEDIATE 'CREATE ROLE IF NOT EXISTS ' || role_name;
        EXECUTE IMMEDIATE 'GRANT USAGE ON WAREHOUSE TML_HACKATHON TO ROLE ' || role_name;
        EXECUTE IMMEDIATE 'GRANT USAGE ON DATABASE TML_FLEET_TELEMETRY TO ROLE ' || role_name;
        EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA TML_FLEET_TELEMETRY.BUSINESSREADY TO ROLE ' || role_name;
        EXECUTE IMMEDIATE 'GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA TML_FLEET_TELEMETRY.BUSINESSREADY TO ROLE ' || role_name;
        EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA TML_FLEET_TELEMETRY.BUSINESSREADY TO ROLE ' || role_name;
        i := i + 1;
    END WHILE;
END;

-- Row Access Policy
CREATE OR REPLACE ROW ACCESS POLICY TML_FLEET_TELEMETRY.BUSINESSREADY.TRIP_CUSTOMER_RAP
AS (CUSTOMER_ID VARCHAR) RETURNS BOOLEAN ->
    CURRENT_ROLE() = 'ACCOUNTADMIN'
    OR CURRENT_ROLE() = CUSTOMER_ID || '_ROLE';

-- Apply to TRIP_SUMMARIES_V1
ALTER DYNAMIC TABLE TML_FLEET_TELEMETRY.BUSINESSREADY.TRIP_SUMMARIES_V1
    ADD ROW ACCESS POLICY TML_FLEET_TELEMETRY.BUSINESSREADY.TRIP_CUSTOMER_RAP ON (CUSTOMER_ID);

-- ────────────────────────────────────────────────────────────────────────────
-- STEP 10: Retention Enforcement — Stored Procedure and Task
-- ────────────────────────────────────────────────────────────────────────────
USE SCHEMA TML_FLEET_TELEMETRY.RAW;

CREATE OR REPLACE PROCEDURE ENFORCE_CUSTOMER_RETENTION()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    total_deleted INT DEFAULT 0;
    cust_deleted INT DEFAULT 0;
    cust_id VARCHAR;
    retention_days INT;
    cur CURSOR FOR
        SELECT CUSTOMER_ID, RAW_RETENTION_DAYS
        FROM TML_FLEET_TELEMETRY.MASTER.CUSTOMER_RETENTION_POLICIES;
BEGIN
    FOR rec IN cur DO
        cust_id := rec.CUSTOMER_ID;
        retention_days := rec.RAW_RETENTION_DAYS;

        DELETE FROM TML_FLEET_TELEMETRY.RAW.VEHICLE_TELEMETRY_RAW_V1
        WHERE CUSTOMER_ID = :cust_id
          AND EVENT_TS < DATEADD('DAY', -1 * :retention_days, CURRENT_TIMESTAMP());

        cust_deleted := SQLROWCOUNT;
        total_deleted := total_deleted + cust_deleted;
    END FOR;

    RETURN 'RAW retention enforced. Total rows deleted: ' || total_deleted::VARCHAR;
END;
$$;

CREATE OR REPLACE TASK CUSTOMER_RETENTION_TASK
    WAREHOUSE = TML_HACKATHON
    SCHEDULE = 'USING CRON 0 2 * * * UTC'
    COMMENT = 'Daily customer-specific retention enforcement. Deletions propagate through CURATED DTs to BUSINESSREADY.'
AS
CALL TML_FLEET_TELEMETRY.RAW.ENFORCE_CUSTOMER_RETENTION();

-- Activate the task (uncomment when ready)
-- ALTER TASK CUSTOMER_RETENTION_TASK RESUME;

-- ────────────────────────────────────────────────────────────────────────────
-- STEP 11: Verification Queries
-- ────────────────────────────────────────────────────────────────────────────

-- RAW row count
SELECT COUNT(*) AS raw_row_count FROM TML_FLEET_TELEMETRY.RAW.VEHICLE_TELEMETRY_RAW_V1;

-- CURATED DT status
SHOW DYNAMIC TABLES LIKE '%_V1' IN SCHEMA TML_FLEET_TELEMETRY.CURATED;

-- BUSINESSREADY DT status
SHOW DYNAMIC TABLES LIKE '%_V1' IN SCHEMA TML_FLEET_TELEMETRY.BUSINESSREADY;

-- ARRIVED_LATE distribution
SELECT ARRIVED_LATE, COUNT(*), ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 1) AS PCT
FROM TML_FLEET_TELEMETRY.CURATED.GPS_SIGNALS_V1
GROUP BY ARRIVED_LATE;

-- Schema evolution check
SELECT COUNT(*) AS total, COUNT(J1939_TYRE_PRESSURE_FRONT_LEFT_KPA) AS evolved
FROM TML_FLEET_TELEMETRY.RAW.VEHICLE_TELEMETRY_RAW_V1;

-- Test retention proc
CALL TML_FLEET_TELEMETRY.RAW.ENFORCE_CUSTOMER_RETENTION();

-- Test RAP: switch to a customer role
-- USE ROLE CUST_0001_ROLE;
-- SELECT COUNT(*) FROM TML_FLEET_TELEMETRY.BUSINESSREADY.TRIP_SUMMARIES_V1;
